algoritmo "Contar até 10"
var
numero: Real
i: inteiro
inicio
numero <- 0

// interrompa == break, se quiser interromper o bloco enquanto

enquanto numero < 10 faca
    numero <- numero + 1
    escreval(numero)
fimenquanto

numero <- 0

repita
    numero <- numero + 1
    escreval(numero)
ate numero = 10

numero <- 0

para i de 1 ate 11 passo 1 faca
    escreval(numero)
    numero <- numero + 1
fimpara
fimalgoritmo


