algoritmo "Função"

var

n1, n2: inteiro

//     função  parâmetros  retorno
funcao somar(a, b: inteiro): inteiro

inicio

retorne a + b

fimfuncao

funcao resultado(): caracter

inicio

escreva("resultado")

fimfuncao

inicio

escreval("Digite os números que serão somados: ")
leia(n1)
escreval("e")
leia(n2)
escreva(resultado())
escreval(somar(n1, n2))

fimalgoritmo
